---
settings:
  name: NetApp solutions for SAP
  internal:
    pdf_enabled: true
  prod:
    pdf_enabled: true
    harmony_enabled: false
  langs: zh-tw,us-en,de-de,es-es,fr-fr,it-it,pt-br,ja-jp,ko-kr,zh-cn
sidebar:
  entries:
  - title: SAP 解決方案
    url: "/index.html"
  - title: 什麼是新的
    url: "/whats-new.html"
  - section: bp
  - section: backup
  - section: lifecycle
  - section: briefs
  - title: 法律聲明
    url: "/legal-notices.html"
product-family:
  name: NetApp solutions
  repo: netapp-solutions-family
