---
sidebar: sidebar 
permalink: backup/hana-sc-vmware-smas-sc-restore.html 
keywords: SAP HANA, VMware, SnapMirror active sync, SnapCenter, backup and recovery 
summary:  
---
= SnapCenter 還原與還原
:allow-uri-read: 


'''
當虛擬資源儲存在 VMPS/VMDK 上時， SnapCenter 還原作業一律會透過複製，掛載，複製作業來完成。

. SnapCenter 會根據所選的 Snapshot 建立 Volume Clone
. SnapCenter 將 LUN 作爲新的資料存放區裝載到 ESX 主機中
. SnapCenter 將資料存放區內的 VMDK 新增為 HANA VM 的新磁碟
. SnapCenter 會將新磁碟裝載到 Linux 作業系統
. SnapCenter 會將資料從新磁碟複製回原始位置
. 複製作業完成後，上述所有資源都會再次移除
. HANA 恢復工作如常進行


因此，還原作業的整體執行時間會因儲存叢集與 ESX 主機之間的資料庫大小和 FC 連線處理量而定。

此外，當資源設定為 SnapMirror 作用中同步時， SnapCenter 還原作業只能在目前的主要站台上選取。

5f35033b3e56e00e68892ec016ea328f

還原與還原作業正在執行時，您可以看到新的複製磁碟區，該磁碟區是在目前的主要站台建立的。

6f06150d9d62fe339c9d504278327de4

在 HANA Linux 主機上，您可以看到裝載到主機上的新磁碟。還原作業完成後， SnapCenter 會再次移除資料存放區和磁碟區。

....
hana-1:~ # df -h
Filesystem Size Used Avail Use% Mounted on
devtmpfs 4.0M 8.0K 4.0M 1% /dev
tmpfs 49G 4.0K 49G 1% /dev/shm
tmpfs 13G 58M 13G 1% /run
tmpfs 4.0M 0 4.0M 0% /sys/fs/cgroup
/dev/mapper/system-root 60G 36G 24G 60% /
/dev/mapper/system-root 60G 36G 24G 60% /.snapshots
/dev/mapper/system-root 60G 36G 24G 60% /boot/grub2/i386-pc
/dev/mapper/system-root 60G 36G 24G 60% /home
/dev/mapper/system-root 60G 36G 24G 60% /boot/grub2/x86_64-efi
/dev/mapper/system-root 60G 36G 24G 60% /opt
/dev/mapper/system-root 60G 36G 24G 60% /srv
/dev/mapper/system-root 60G 36G 24G 60% /usr/local
/dev/mapper/system-root 60G 36G 24G 60% /tmp
/dev/mapper/system-root 60G 36G 24G 60% /root
/dev/mapper/system-root 60G 36G 24G 60% /var
/dev/sdb 200G 8.0G 192G 4% /hana/data/SMA/mnt00001
/dev/sdc 120G 7.0G 113G 6% /hana/log/SMA/mnt00001
/dev/sda1 253M 5.1M 247M 3% /boot/efi
/dev/sdd 150G 28G 123G 19% /hana/shared
tmpfs 6.3G 48K 6.3G 1% /run/user/467
tmpfs 6.3G 28K 6.3G 1% /run/user/0
/dev/sde 200G 8.0G 192G 4% /var/opt/snapcenter/scu/clones/hana_data_SMAmnt00001_255_scu_clone_1
hana-1:~ #
....