---
sidebar: sidebar 
permalink: backup/hana-hycl-backup-conf.html 
keywords: BlueXP, SAP HANA, configuration 
summary: 本節說明如何設定工作環境、如何設定 SnapCenter 、以及如何在 BlueXP 中設定及啟動 SAP HANA 備份。 
---
= 設定 SAP HANA 的 BlueXP 備份與恢復
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./../media/




== 為 BlueXP 建立工作環境

將內部部署儲存系統新增至您的工作環境。

. 在左功能表中選擇 * 儲存 * -> * 畫布 * -> * 我的工作 * 環境。
. 按 *+ 新增工作環境 * 。+ 圖片： hana-hycl-back-image2.jpeg[hana-hycl-back-image2,width=624,height=316]
. 選擇 * 內部部署 * 。+ 影像： hana-hycl-back-image3.jpeg[Ein Bild 、 das Text en ä lt 。Automatisch generierte Beschreibung,width=62,height=316]
. 選擇 * 探索內部部署的 ONTAP * 。+ 影像： hana-hycl-back-image4.jpeg[Ein Bild 、 das Text en ä lt 。Automatisch generierte Beschreibung,width=62,height=316]
. 新增 ONTAP 叢集的 IP 位址和密碼、然後按 * 探索 * 。+ 圖片： hana-hycl-back-image5.jpeg[hana-hycl-back-image5,width=624,height=316]
. ONTAP 叢集現在可供使用。+ 圖片： hana-hycl-back-image6.jpeg[Ein Bild 、 das Diagramm enthä lt 。Automatisch generierte Beschreibung,width=62,height=316]




== 在內部部署儲存系統和物件儲存貯體之間建立關係

內部儲存設備與 S3 儲存區之間的關係是透過建立磁碟區的備份或啟動應用程式的備份來達成。如果將現有的站台對站台 VPN 用於將資料從內部部署傳輸到 S3 、則需要使用磁碟區備份來建立內部部署儲存設備與 S3 儲存區之間的關係、做為 VPC 端點。+
建立此文件時、應用程式備份工作流程並未提供選擇 VPC 端點來存取 S3 儲存區的功能。+
請參閱 https://docs.aws.amazon.com/vpc/latest/privatelink/vpc-endpoints-s3.html["Amazon S3 的閘道端點： Amazon Virtual Private Cloud"] 如何在 VPC 中設定 S3 的 VPC 端點。

若要建立第一個磁碟區備份、請執行下列步驟：

. 瀏覽 * 保護 * 至 * 備份與恢復 * 、然後選擇 * 磁碟區 * 。+ 圖片： hana-hycl-back-image7.jpeg[hana-hycl-back-image7,width=624,height=308]
. 按 * 啟動備份 * 按鈕。+ 圖片： hana-hycl-back-image8.jpeg[hana-hycl-back-image8,width=624,height=309]
. 選擇所需的內部部署儲存系統、然後按一下 * 啟動備份 * 。+ 圖片： hana-hycl-back-image9.jpeg[hana-hycl-back-image9,width=624,height=304]
. 選擇 * 備份 * 。+ 圖片： hana-hycl-back-image10.jpeg[hana-hycl-back-image10,width=624,height=307]
. 選擇與 SAP HANA 資料檔案儲存在同一個 SVM 的 Volume 、然後按下 * 下一步 * 。在此範例中、已選擇 /Hana / Shared 的磁碟區。+ 圖片： hana-hycl-back-image12.jpeg[hana-hycl-back-image12,width=624,height=305]
. * 繼續 * （如果存在現有策略）。+ 圖片： hana-hycl-back-image11.jpeg[hana-hycl-back-image11,width=624,height=304]
. 請勾選 * 備份選項 * 、然後選擇您想要的備份供應商。在此 AWS 範例中。+ 核取已有原則的選項。+ 取消核取您不想使用的選項。+ 影像： hana-hycl-back-image13.jpeg[Ein Bild 、 das Text 、 Software 、 Computersymbol 、 Webseite enthä lt 。Automatisch generierte Beschreibung,width=62,height =306]
. 建立新的貯體或選擇現有的貯體。提供 AWS 帳戶設定、區域、存取金鑰和秘密金鑰。按 * 下一步 * 。+ 圖片： hana-hycl-back-image14.jpeg[hana-hycl-back-image14,width=624,height=306]
. 選擇內部部署儲存系統的正確 IPspace 、選取 * 私有端點組態 * 、然後選擇 S3 的 VPC 端點。按 * 下一步 * 。+ 圖片： hana-hycl-back-image15.jpeg[hana-hycl-back-image15,width=624,height=304]
. 檢閱您的組態並按下 * 啟動備份 * 。+ 圖片： hana-hycl-back-image16.jpeg[hana-hycl-back-image16,width=624,height=304]
. 備份已成功初始化。+ 圖片： hana-hycl-back-image17.jpeg[hana-hycl-back-image17,width=624,height=304]




== 在 SnapCenter 設定 SAP HANA 系統資源

. 請檢查是否已透過叢集新增儲存 SAP HANA 系統的 SVM （本範例中為 Hana ）。如果只新增 SVM 、請新增叢集。+ 影像： hana hycl-back image18-png[ 自動產生圖形化使用者介面、應用程式說明、寬度 = 604 、高度 = 156]
. 使用每日、每週或每月排程類型來定義排程原則。+ 影像： Hana hycl-back － image19.pn[Graphical User Interface, Application Description automatically Generated 、 width=604 、 height =140] 影像：： hana-hycl-back-image20.jpeg[hana-hycl-back-image20,width=167,height=167]
. 將新原則新增至 SAP HANA 系統、並指派每日排程。+ 影像： hana hycl-back image21.png[ 自動產生圖形化使用者介面、應用程式說明、寬度 = 604 、高度 = 21]
. 根據定義的排程執行原則之後、即可使用此原則設定的新備份。 影像： Hana hycl-back image22.png[ 自動產生圖形化使用者介面、應用程式、團隊說明、寬度 = 604 、高度 = 193]




== 將 SnapCenter 新增至 BlueXP 工作環境

. 在左功能表中選擇 * 保護 * -> * 備份與恢復 * -> * 應用程式 * 。
. 從下拉式功能表中選擇 * 混合 * 。+ 圖片： hana-hycl-back-image23.jpeg[hana-hycl-back-image23,width=624,height=316]
. 在「設定」功能表中選擇 * SnapCenter Servers* 。+ 影像： hana-hycl-back-image24.jpeg[Ein Bild 、 das Text en ä lt 。Automatisch generierte Beschreibung,width=62,height=316]
. 註冊 SnapCenter 伺服器。+ 影像： hana-hycl-back-image25.jpeg[Ein Bild 、 das Text en ä lt 。Automatisch generierte Beschreibung,width=62,height=316]
. 新增 SnapCenter 伺服器認證。+ 圖片： hana-hycl-back-image26.jpeg[hana-hycl-back-image26,width=624,height=315]
. 已新增 SnapCenter 伺服器、並將探索到資料。+ 圖片： hana-hycl-back-image27.jpeg[hana-hycl-back-image27,width=624,height=316]
. 一旦完成探索工作、 SAP HANA 系統就能使用。+ 影像： hana-hycl-back-image28.jpeg[Ein Bild 、 das Text en ä lt 。Automatisch generierte Beschreibung,width=62,height=316]




== 建立應用程式備份的備份原則

. 在設定功能表中選擇 * 原則 * 。+ 圖片： hana-hycl-back-image29.jpeg[hana-hycl-back-image29,width=624,height=316]
. 如有需要、請按一下 * 建立原則 * 來建立新原則。+ 圖片： hana-hycl-back-image30.jpeg[hana-hycl-back-image30,width=624,height=316]
. 提供原則名稱、所需的 SnapMirror 標籤、選擇所需的選項、然後按 * Create * 。+ 圖片： hana-hycl-back-image31.jpeg[hana-hycl-back-image31,width=624,height=315]
. 新原則可供使用。+ 圖片： hana-hycl-back-image32.jpeg[hana-hycl-back-image32,width=624,height=315]




== 利用 Cloud Backup for Applications 保護 SAP HANA 資料庫

. 選擇 * 啟動 SAP HANA 系統的備份 * 。+ 圖片： hana-hycl-back-image33.jpeg[width=624,height=316]
. 選擇先前建立的原則、然後按一下 * 下一步 * 。+ 圖片： hana-hycl-back-image34.jpeg[width=624,height=316]
. 由於儲存系統和連接器已預先設定、備份將會啟動。+ 圖片： hana-hycl-back-image35.jpeg[width=624,height=316]
. 工作完成後、系統將會列出。+ 圖片： hana-hycl-back-image36.jpeg[width=624,height=337]
. 一段時間後、備份會列在 SAP HANA 系統的詳細檢視畫面中。+ 第二天將列出每日備份。+ 圖片： hana-hycl-back-image37.jpeg[hana-hycl-back-image37,width=624,height=316]


在某些環境中、可能需要移除 SnapMirror 來源的任何現有排程設定。爲此，請在源 ONTAP 系統上執行以下命令： _SnapMirror modify -destination-path <hana-cloud-svm> ： <SID_data_mnt00001> 複製 -schedule "_ 。
