---
sidebar: sidebar 
permalink: backup/saphana-backup-anf-overview.html 
keywords: overview, introduction, tr-4905, 4905, tr4905, snapcenter service, anf, azure netapp files 
summary: 本技術報告涵蓋SAP HANA資料保護的最佳實務做法（採用NetApp SnapCenter 功能和Azure NetApp Files 功能）。其中涵SnapCenter 蓋「不支援服務」概念、組態建議及作業工作流程、包括備份、還原及還原作業。 
---
= TR-4905：SAP HANA利用Azure NetApp Files NetApp服務在支援的基礎上進行備份與恢復SnapCenter
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
本技術報告涵蓋SAP HANA資料保護的最佳實務做法（採用NetApp SnapCenter 功能和Azure NetApp Files 功能）。其中涵SnapCenter 蓋「不支援服務」概念、組態建議及作業工作流程、包括備份、還原及還原作業。

作者： Nils Bauer 、 NetApp

現今的企業需要持續且不中斷的SAP應用程式可用度。他們期望面對不斷增加的資料量、以及系統備份等例行維護工作的需求、能達到一致的效能等級。執行SAP資料庫備份是一項重要工作、可能對正式作業SAP系統造成重大效能影響。

備份時間越來越短、而要備份的資料量卻越來越多。因此、很難找到能夠在對業務程序影響最小的情況下執行備份的時間。還原及還原SAP系統所需的時間是一項重大考量、因為必須將SAP正式作業與非正式作業系統的停機時間降至最低、以減少資料遺失及企業成本。

以下各點概述SAP備份與還原所面臨的挑戰：

* *效能對正式作業SAP系統的影響。*傳統的複製型備份通常會因為資料庫伺服器、儲存系統和儲存網路承受沉重的負載、而在正式作業SAP系統上造成顯著的效能消耗。
* *縮減備份時間。*只有在SAP系統上進行的對話或批次活動很少時、才能進行傳統備份。當SAP系統全天候使用時、備份排程變得更加困難。
* *快速資料成長*快速資料成長與縮減備份時間、需要持續投資備份基礎架構。換句話說、您必須購買額外的備份磁碟空間、並加快備份網路的速度。您也必須負擔儲存及管理這些備份資產的持續費用。遞增或差異備份可以解決這些問題、但這種安排會造成非常緩慢、繁瑣且複雜的還原程序、難以驗證。這類系統通常會以企業無法接受的方式、增加恢復時間目標（RTO）和恢復點目標（RPO）的時間。
* *停機成本增加。* SAP系統的非計畫性停機通常會影響企業財務。在任何非計畫性停機中、有一大部分是因為還原和恢復SAP系統的需求而耗用。因此、所需的RTO決定了備份與還原架構的設計。
* * SAP升級專案的備份與還原時間。* SAP升級專案計畫至少包含三個SAP資料庫備份。這些備份可大幅縮短升級程序的可用時間。決定繼續進行的時間通常取決於從先前建立的備份還原及還原資料庫所需的時間。快速還原不只是將系統還原至先前的狀態、更能提供更多時間來解決升級期間可能發生的問題。

