---
sidebar: sidebar 
permalink: bp/hana-aff-fc-host-setup.html 
keywords: multipathing, fcp, hba, configure 
summary: 在設定主機之前、NetApp SAN主機公用程式必須從NetApp支援網站下載、並安裝在HANA伺服器上。主機公用程式文件包含其他軟體的相關資訊、這些軟體必須視所使用的FCP HBA而安裝。 
---
= 主機設定
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
設定主機之前、必須先從下載NetApp SAN主機公用程式 http://mysupport.netapp.com/["NetApp支援"^] 並安裝在HANA伺服器上。主機公用程式文件包含其他軟體的相關資訊、這些軟體必須視所使用的FCP HBA而安裝。

本文件也包含所使用Linux版本特有的多重路徑組態資訊。本文件涵蓋SLES 12 SP1或更新版本及RHEL 7所需的組態步驟。2或更新版本、如所述 https://library.netapp.com/ecm/ecm_download_file/ECMLP2547958["《Linux主機公用程式7.1安裝與設定指南》"^]。



=== 設定多重路徑


NOTE: 在SAP HANA多主機組態中、必須在所有工作者和待命主機上執行步驟1到6。

若要設定多重路徑、請完成下列步驟：

. 在每個伺服器上執行Linux「scan-scsi-bus.sh -A'」命令、以探索新的LUN。
. 運行 `sanlun lun show`命令並驗證所有必需的 LUN 是否可見。以下範例顯示了 `sanlun lun show`具有兩個資料 LUN 和兩個日誌 LUN 的 2+1 多主機 HANA 系統的命令輸出。輸出顯示 LUN 和相應的設備文件，例如 LUN  `FC5_data_mnt00001`和設備文件 `/dev/sdag`每個 LUN 都有八條從主機到儲存控制器的 FC 路徑。
+
....
sapcc-hana-tst:~ # sanlun lun show
controller(7mode/E-Series)/                                  device          host                  lun
vserver(cDOT/FlashRay)        lun-pathname                   filename        adapter    protocol   size    product
---------------------------------------------------------------------------------------------------------------
svm1                          FC5_log2_mnt00002              /dev/sdbb       host21     FCP        500g    cDOT
svm1                          FC5_log_mnt00002               /dev/sdba       host21     FCP        500g    cDOT
svm1                          FC5_log2_mnt00001              /dev/sdaz       host21     FCP        500g    cDOT
svm1                          FC5_log_mnt00001               /dev/sday       host21     FCP        500g    cDOT
svm1                          FC5_data2_mnt00002             /dev/sdax       host21     FCP        1t      cDOT
svm1                          FC5_data_mnt00002              /dev/sdaw       host21     FCP        1t      cDOT
svm1                          FC5_data2_mnt00001             /dev/sdav       host21     FCP        1t      cDOT
svm1                          FC5_data_mnt00001              /dev/sdau       host21     FCP        1t      cDOT
svm1                          FC5_log2_mnt00002              /dev/sdat       host21     FCP        500g    cDOT
svm1                          FC5_log_mnt00002               /dev/sdas       host21     FCP        500g    cDOT
svm1                          FC5_log2_mnt00001              /dev/sdar       host21     FCP        500g    cDOT
svm1                          FC5_log_mnt00001               /dev/sdaq       host21     FCP        500g    cDOT
svm1                          FC5_data2_mnt00002             /dev/sdap       host21     FCP        1t      cDOT
svm1                          FC5_data_mnt00002              /dev/sdao       host21     FCP        1t      cDOT
svm1                          FC5_data2_mnt00001             /dev/sdan       host21     FCP        1t      cDOT
svm1                          FC5_data_mnt00001              /dev/sdam       host21     FCP        1t      cDOT
svm1                          FC5_log2_mnt00002              /dev/sdal       host20     FCP        500g    cDOT
svm1                          FC5_log_mnt00002               /dev/sdak       host20     FCP        500g    cDOT
svm1                          FC5_log2_mnt00001              /dev/sdaj       host20     FCP        500g    cDOT
svm1                          FC5_log_mnt00001               /dev/sdai       host20     FCP        500g    cDOT
svm1                          FC5_data2_mnt00002             /dev/sdah       host20     FCP        1t      cDOT
svm1                          FC5_data_mnt00002              /dev/sdag       host20     FCP        1t      cDOT
svm1                          FC5_data2_mnt00001             /dev/sdaf       host20     FCP        1t      cDOT
svm1                          FC5_data_mnt00001              /dev/sdae       host20     FCP        1t      cDOT
svm1                          FC5_log2_mnt00002              /dev/sdad       host20     FCP        500g    cDOT
svm1                          FC5_log_mnt00002               /dev/sdac       host20     FCP        500g    cDOT
svm1                          FC5_log2_mnt00001              /dev/sdab       host20     FCP        500g    cDOT
svm1                          FC5_log_mnt00001               /dev/sdaa       host20     FCP        500g    cDOT
svm1                          FC5_data2_mnt00002             /dev/sdz        host20     FCP        1t      cDOT
svm1                          FC5_data_mnt00002              /dev/sdy        host20     FCP        1t      cDOT
svm1                          FC5_data2_mnt00001             /dev/sdx        host20     FCP        1t      cDOT
svm1                          FC5_data_mnt00001              /dev/sdw        host20     FCP        1t      cDOT

....
. 運行 `multipath -r`和 `multipath -ll`命令取得裝置檔案名稱的全球識別碼 (WWID)。
+

NOTE: 在此範例中，有 8 個 LUN。

+
....
sapcc-hana-tst:~ # multipath -r
sapcc-hana-tst:~ # multipath -ll
3600a098038314e63492b59326b4b786d dm-7 NETAPP,LUN C-Mode
size=1.0T features='3 queue_if_no_path pg_init_retries 50' hwhandler='1 alua' wp=rw
`-+- policy='service-time 0' prio=50 status=active
  |- 20:0:4:2 sdaf 65:240 active ready running
  |- 20:0:5:2 sdx  65:112 active ready running
  |- 21:0:4:2 sdav 66:240 active ready running
  `- 21:0:6:2 sdan 66:112 active ready running
3600a098038314e63492b59326b4b786e dm-9 NETAPP,LUN C-Mode
size=1.0T features='3 queue_if_no_path pg_init_retries 50' hwhandler='1 alua' wp=rw
`-+- policy='service-time 0' prio=50 status=active
  |- 20:0:4:4 sdah 66:16  active ready running
  |- 20:0:5:4 sdz  65:144 active ready running
  |- 21:0:4:4 sdax 67:16  active ready running
  `- 21:0:6:4 sdap 66:144 active ready running
3600a098038314e63492b59326b4b786f dm-11 NETAPP,LUN C-Mode
size=500G features='3 queue_if_no_path pg_init_retries 50' hwhandler='1 alua' wp=rw
`-+- policy='service-time 0' prio=50 status=active
  |- 20:0:4:6 sdaj 66:48  active ready running
  |- 20:0:5:6 sdab 65:176 active ready running
  |- 21:0:4:6 sdaz 67:48  active ready running
  `- 21:0:6:6 sdar 66:176 active ready running
3600a098038314e63492b59326b4b7870 dm-13 NETAPP,LUN C-Mode
size=500G features='3 queue_if_no_path pg_init_retries 50' hwhandler='1 alua' wp=rw
`-+- policy='service-time 0' prio=50 status=active
  |- 20:0:4:8 sdal 66:80  active ready running
  |- 20:0:5:8 sdad 65:208 active ready running
  |- 21:0:4:8 sdbb 67:80  active ready running
  `- 21:0:6:8 sdat 66:208 active ready running
3600a098038314e63532459326d495a64 dm-6 NETAPP,LUN C-Mode
size=1.0T features='3 queue_if_no_path pg_init_retries 50' hwhandler='1 alua' wp=rw
`-+- policy='service-time 0' prio=50 status=active
  |- 20:0:4:1 sdae 65:224 active ready running
  |- 20:0:5:1 sdw  65:96  active ready running
  |- 21:0:4:1 sdau 66:224 active ready running
  `- 21:0:6:1 sdam 66:96  active ready running
3600a098038314e63532459326d495a65 dm-8 NETAPP,LUN C-Mode
size=1.0T features='3 queue_if_no_path pg_init_retries 50' hwhandler='1 alua' wp=rw
`-+- policy='service-time 0' prio=50 status=active
  |- 20:0:4:3 sdag 66:0   active ready running
  |- 20:0:5:3 sdy  65:128 active ready running
  |- 21:0:4:3 sdaw 67:0   active ready running
  `- 21:0:6:3 sdao 66:128 active ready running
3600a098038314e63532459326d495a66 dm-10 NETAPP,LUN C-Mode
size=500G features='3 queue_if_no_path pg_init_retries 50' hwhandler='1 alua' wp=rw
`-+- policy='service-time 0' prio=50 status=active
  |- 20:0:4:5 sdai 66:32  active ready running
  |- 20:0:5:5 sdaa 65:160 active ready running
  |- 21:0:4:5 sday 67:32  active ready running
  `- 21:0:6:5 sdaq 66:160 active ready running
3600a098038314e63532459326d495a67 dm-12 NETAPP,LUN C-Mode
size=500G features='3 queue_if_no_path pg_init_retries 50' hwhandler='1 alua' wp=rw
`-+- policy='service-time 0' prio=50 status=active
  |- 20:0:4:7 sdak 66:64  active ready running
  |- 20:0:5:7 sdac 65:192 active ready running
  |- 21:0:4:7 sdba 67:64  active ready running
  `- 21:0:6:7 sdas 66:192 active ready running

....
. 編輯「/etc/multipath.conf」檔案、然後新增WWID和別名。
+

NOTE: 輸出範例顯示/etc/multipath.conf檔案的內容、其中包含2+1多主機系統四個LUN的別名。如果沒有可用的多重路徑.conf檔案、您可以執行下列命令來建立檔案：「多重路徑-T >/etc/multipath.conf」。

+
....
sapcc-hana-tst:/ # cat /etc/multipath.conf
multipaths {
                multipath {
                wwid    3600a098038314e63492b59326b4b786d
                alias   svm1-FC5_data2_mnt00001
        }
        multipath {
                wwid    3600a098038314e63492b59326b4b786e
                alias   svm1-FC5_data2_mnt00002
        }
        multipath {
                wwid    3600a098038314e63532459326d495a64
                alias   svm1-FC5_data_mnt00001
        }
        multipath {
                wwid    3600a098038314e63532459326d495a65
                alias   svm1-FC5_data_mnt00002
        }
        multipath {
                wwid    3600a098038314e63492b59326b4b786f
                alias   svm1-FC5_log2_mnt00001
        }
        multipath {
                wwid    3600a098038314e63492b59326b4b7870
                alias   svm1-FC5_log2_mnt00002
        }
        multipath {
                wwid    3600a098038314e63532459326d495a66
                alias   svm1-FC5_log_mnt00001
        }
        multipath {
                wwid    3600a098038314e63532459326d495a67
                alias   svm1-FC5_log_mnt00002
        }


}
....
. 執行「multiPath-r」命令重新載入裝置對應。
. 執行「multiPath-ll」命令來列出所有LUN、別名、作用中和待命路徑、以驗證組態。
+

NOTE: 下列輸出範例顯示2+1多主機HANA系統的輸出、其中包含兩個資料和兩個記錄LUN。

+
....
sapcc-hana-tst:~ # multipath -ll
hsvm1-FC5_data2_mnt00001 (3600a098038314e63492b59326b4b786d) dm-7 NETAPP,LUN C-Mode
size=1.0T features='3 queue_if_no_path pg_init_retries 50' hwhandler='1 alua' wp=rw
`-+- policy='service-time 0' prio=50 status=active
  |- 20:0:4:2 sdaf 65:240 active ready running
  |- 20:0:5:2 sdx  65:112 active ready running
  |- 21:0:4:2 sdav 66:240 active ready running
  `- 21:0:6:2 sdan 66:112 active ready running
svm1-FC5_data2_mnt00002 (3600a098038314e63492b59326b4b786e) dm-9 NETAPP,LUN C-Mode
size=1.0T features='3 queue_if_no_path pg_init_retries 50' hwhandler='1 alua' wp=rw
`-+- policy='service-time 0' prio=50 status=active
  |- 20:0:4:4 sdah 66:16  active ready running
  |- 20:0:5:4 sdz  65:144 active ready running
  |- 21:0:4:4 sdax 67:16  active ready running
  `- 21:0:6:4 sdap 66:144 active ready running
svm1-FC5_data_mnt00001 (3600a098038314e63532459326d495a64) dm-6 NETAPP,LUN C-Mode
size=1.0T features='3 queue_if_no_path pg_init_retries 50' hwhandler='1 alua' wp=rw
`-+- policy='service-time 0' prio=50 status=active
  |- 20:0:4:1 sdae 65:224 active ready running
  |- 20:0:5:1 sdw  65:96  active ready running
  |- 21:0:4:1 sdau 66:224 active ready running
  `- 21:0:6:1 sdam 66:96  active ready running
svm1-FC5_data_mnt00002 (3600a098038314e63532459326d495a65) dm-8 NETAPP,LUN C-Mode
size=1.0T features='3 queue_if_no_path pg_init_retries 50' hwhandler='1 alua' wp=rw
`-+- policy='service-time 0' prio=50 status=active
  |- 20:0:4:3 sdag 66:0   active ready running
  |- 20:0:5:3 sdy  65:128 active ready running
  |- 21:0:4:3 sdaw 67:0   active ready running
  `- 21:0:6:3 sdao 66:128 active ready running
svm1-FC5_log2_mnt00001 (3600a098038314e63492b59326b4b786f) dm-11 NETAPP,LUN C-Mode
size=500G features='3 queue_if_no_path pg_init_retries 50' hwhandler='1 alua' wp=rw
`-+- policy='service-time 0' prio=50 status=active
  |- 20:0:4:6 sdaj 66:48  active ready running
  |- 20:0:5:6 sdab 65:176 active ready running
  |- 21:0:4:6 sdaz 67:48  active ready running
  `- 21:0:6:6 sdar 66:176 active ready running
svm1-FC5_log2_mnt00002 (3600a098038314e63492b59326b4b7870) dm-13 NETAPP,LUN C-Mode
size=500G features='3 queue_if_no_path pg_init_retries 50' hwhandler='1 alua' wp=rw
`-+- policy='service-time 0' prio=50 status=active
  |- 20:0:4:8 sdal 66:80  active ready running
  |- 20:0:5:8 sdad 65:208 active ready running
  |- 21:0:4:8 sdbb 67:80  active ready running
  `- 21:0:6:8 sdat 66:208 active ready running
svm1-FC5_log_mnt00001 (3600a098038314e63532459326d495a66) dm-10 NETAPP,LUN C-Mode
size=500G features='3 queue_if_no_path pg_init_retries 50' hwhandler='1 alua' wp=rw
`-+- policy='service-time 0' prio=50 status=active
  |- 20:0:4:5 sdai 66:32  active ready running
  |- 20:0:5:5 sdaa 65:160 active ready running
  |- 21:0:4:5 sday 67:32  active ready running
  `- 21:0:6:5 sdaq 66:160 active ready running
svm1-FC5_log_mnt00002 (3600a098038314e63532459326d495a67) dm-12 NETAPP,LUN C-Mode
size=500G features='3 queue_if_no_path pg_init_retries 50' hwhandler='1 alua' wp=rw
`-+- policy='service-time 0' prio=50 status=active
  |- 20:0:4:7 sdak 66:64  active ready running
  |- 20:0:5:7 sdac 65:192 active ready running
  |- 21:0:4:7 sdba 67:64  active ready running
  `- 21:0:6:7 sdas 66:192 active ready running

....

