---
sidebar: sidebar 
permalink: bp/hana-fas-nfs-install-prep-nfsv4.html 
keywords: sap, hana, installation, preparations, nfsv4, user, authentication, storage, controller, hosts 
summary: NFS版本4及更新版本需要使用者驗證。此驗證可透過使用集中式使用者管理工具（例如輕量型目錄存取傳輸協定（LDAP）伺服器或本機使用者帳戶）來完成。 
---
= NFSv4的SAP HANA安裝準備
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
NFS版本4及更新版本需要使用者驗證。此驗證可透過使用集中式使用者管理工具（例如輕量型目錄存取傳輸協定（LDAP）伺服器或本機使用者帳戶）來完成。下列各節將說明如何設定本機使用者帳戶。

 `sapsys`在開始安裝 SAP HANA 軟體之前，必須在 SAP HANA 主機和儲存控制器上手動建立管理使用者 `<sid>adm`,`<sid>crypt`和群組。



== SAP HANA主機

如果不存在、則必須在SAP HANA主機上建立「最大化」群組。您必須選擇不與儲存控制器上現有群組ID衝突的唯一群組ID。

使用者 `<sid>adm`和 `<sid>crypt`在 SAP HANA 主機上建立。必須選擇與儲存控制器上現有使用者 ID 不衝突的唯一 ID 。

對於多主機 SAP HANA 系統，所有 SAP HANA 主機上的使用者和群組 ID 都必須相同。群組和使用者是在其他 SAP HANA 主機上建立，方法是將來源系統中 `/etc/passwd`受影響的線路複製 `/etc/group`到所有其他 SAP HANA 主機。


NOTE: NFSv4網域必須在所有的Linux伺服器（`/etc/idmapd.conf）和SVM上設為相同的值。在Linux主機的檔案「/etc/idmapd.conf」中設定網域參數「Domain =<domain-name>」。

啟用並啟動NFS idmapd服務。

....
systemctl enable nfs-idmapd.service
systemctl start nfs-idmapd.service
....

NOTE: 最新的Linux核心不需要執行此步驟。警告訊息可以安全地忽略。



== 儲存控制器

SAP HANA 主機和儲存控制器上的使用者 ID 和群組 ID 必須相同。在儲存叢集上輸入下列命令即可建立群組和使用者：

....
vserver services unix-group create -vserver <vserver> -name <group name> -id <group id>
vserver services unix-user create -vserver <vserver> -user <user name> -id <user-id> -primary-gid <group id>
....
此外、請將SVM的UNIX使用者根目錄的群組ID設為0。

....
vserver services unix-user modify -vserver <vserver> -user root -primary-gid 0
....