---
sidebar: sidebar 
permalink: bp/hana-aff-fc-host-setup_single.html 
keywords: multipathing, fcp, hba, configure 
summary: 在設定主機之前、NetApp SAN主機公用程式必須從NetApp支援網站下載、並安裝在HANA伺服器上。主機公用程式文件包含其他軟體的相關資訊、這些軟體必須視所使用的FCP HBA而安裝。 
---
= 單主機設定
:allow-uri-read: 




== 單主機設定

[role="lead"]
本章介紹使用 LINUX LVM 設定 SAP HANA 單主機。



== SAP HANA 單主機系統的 LUN 配置

在SAP HANA主機上、需要建立和掛載Volume群組和邏輯磁碟區、如下表所示。

|===
| 邏輯磁碟區/LUN | SAP HANA主機的掛載點 | 附註 


| LV：FC5_data_mnt0000-vol | /hana/資料/FC51/mnt00001 | 使用/etc/Fstab項目掛載 


| LV：FC5_log_mnt00001-vol | /HANA / log / FC5/mnt00001 | 使用/etc/Fstab項目掛載 


| LUN：FC5_共享 | /HANA /共享/ FC5 | 使用/etc/Fstab項目掛載 
|===

NOTE: 透過所述配置， `/usr/sap/FC5`儲存使用者 FC5adm 的預設主目錄的目錄位於本機磁碟上。在基於磁碟的複製災難復原設定中， NetApp建議在 `FC5_shared`音量為 `/usr/sap/FC5`目錄，以便所有檔案系統都位於中央儲存空間上。



=== 建立LVM Volume群組和邏輯磁碟區

. 將所有LUN初始化為實體磁碟區。
+
....
pvcreate /dev/mapper/hana-FC5_data_mnt00001
pvcreate /dev/mapper/hana-FC5_data2_mnt00001
pvcreate /dev/mapper/hana-FC5_log_mnt00001
pvcreate /dev/mapper/hana-FC5_log2_mnt00001
....
. 為每個資料和記錄分割區建立磁碟區群組。
+
....
vgcreate FC5_data_mnt00001 /dev/mapper/hana-FC5_data_mnt00001 /dev/mapper/hana-FC5_data2_mnt00001
vgcreate FC5_log_mnt00001 /dev/mapper/hana-FC5_log_mnt00001 /dev/mapper/hana-FC5_log2_mnt00001
....
. 為每個資料和記錄分割區建立邏輯磁碟區。使用等量磁碟區大小、等於每個磁碟區群組使用的LUN數量（在此範例中為兩個）、而資料使用的等量磁碟區大小為256k、記錄使用64k。SAP僅支援每個Volume群組一個邏輯Volume。
+
....
lvcreate --extents 100%FREE -i 2 -I 256k --name vol FC5_data_mnt00001
lvcreate --extents 100%FREE -i 2 -I 64k --name vol FC5_log_mnt00001
....
. 掃描所有其他主機上的實體磁碟區、磁碟區群組和磁碟區群組。


....
modprobe dm_mod
pvscan
vgscan
lvscan
....

NOTE: 如果這些命令找不到磁碟區、則需要重新啟動。

若要掛載邏輯磁碟區、必須啟動邏輯磁碟區。若要啟動磁碟區、請執行下列命令：

....
vgchange -a y
....


=== 建立檔案系統

在所有資料和日誌邏輯磁碟區以及 hana 共用 LUN 上建立 XFS 檔案系統。

....
mkfs.xfs FC5_data_mnt00001-vol
mkfs.xfs FC5_log_mnt00001-vol
mkfs.xfs /dev/mapper/svm1-FC5_shared
....


=== 建立掛載點

建立所需的掛載點目錄，並在資料庫主機上設定權限：

....
sapcc-hana-tst:/ # mkdir -p /hana/data/FC5/mnt00001
sapcc-hana-tst:/ # mkdir -p /hana/log/FC5/mnt00001
sapcc-hana-tst:/ # mkdir -p /hana/shared
sapcc-hana-tst:/ # chmod –R 777 /hana/log/FC5
sapcc-hana-tst:/ # chmod –R 777 /hana/data/FC5
sapcc-hana-tst:/ # chmod 777 /hana/shared
....


=== 掛載檔案系統

使用以下方式在系統啟動期間掛載檔案系統 `/etc/fstab`配置文件，將所需的文件系統新增至 `/etc/fstab`設定檔：

....
# cat /etc/fstab
/dev/mapper/hana-FC5_shared /hana/shared xfs defaults 0 0
/dev/mapper/FC5_log_mnt00001-vol /hana/log/FC5/mnt00001 xfs relatime,inode64 0 0
/dev/mapper/FC5_data_mnt00001-vol /hana/data/FC5/mnt00001 xfs relatime,inode64 0 0
....

NOTE: 用於資料和記錄LUN的XFS檔案系統必須使用「RELatime」和「inode64」掛載選項掛載。

若要掛載檔案系統，請執行 `mount –a`在主機上執行指令。
