---
sidebar: sidebar 
permalink: bp/saphana_aff_nfs_sap_hana_installation_preparations_for_nfsv4.html 
keywords:  
summary: NFS版本4及更新版本需要使用者驗證。此驗證可透過使用集中式使用者管理工具（例如輕量型目錄存取傳輸協定（LDAP）伺服器或本機使用者帳戶）來完成。下列各節將說明如何設定本機使用者帳戶。 
---
= NFSv4的SAP HANA安裝準備
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
NFS版本4及更新版本需要使用者驗證。此驗證可透過使用集中式使用者管理工具（例如輕量型目錄存取傳輸協定（LDAP）伺服器或本機使用者帳戶）來完成。下列各節將說明如何設定本機使用者帳戶。

在SAP HANA軟體開始安裝之前、必須在SAP HANA主機和儲存控制器上手動建立管理使用者「<idadm>'」和「sapsys」群組。



== SAP HANA主機

如果尚未存在、您必須在SAP HANA主機上建立「sapsys」群組。請選擇不與儲存控制器上現有群組ID衝突的唯一群組ID。

使用者「<idadm>'」是在SAP HANA主機上建立。必須選擇不與儲存控制器上現有使用者ID衝突的唯一ID。

對於多主機SAP HANA系統、所有SAP HANA主機上的使用者和群組ID必須相同。群組和使用者是在其他SAP HANA主機上建立、方法是將來源系統中的「/etc/group」和「/etc/passwd」中受影響的線路複製到所有其他SAP HANA主機。


NOTE: 所有Linux伺服器和SVM上的NFSv4網域必須設為相同的值。將Linux主機的檔案「/etc/idmapd.conf」中的網域參數「Domain =<domain_name>」設定為「DOMEN =<domain_name>」。

啟用並啟動NFS idmapd服務：

....
systemctl enable nfs-idmapd.service
systemctl start nfs-idmapd.service
....

NOTE: 最新的Linux核心不需要執行此步驟。您可以安全地忽略警告訊息。



== 儲存控制器

SAP HANA主機和儲存控制器上的使用者ID和群組ID必須相同。在儲存叢集上輸入下列命令即可建立群組和使用者：

....
vserver services unix-group create -vserver <vserver> -name <group name> -id <group id>
vserver services unix-user create -vserver <vserver> -user <user name> -id <user-id> -primary-gid <group id>
....
此外、請將SVM的UNIX使用者根目錄的群組ID設為0。

....
vserver services unix-user modify -vserver <vserver> -user root -primary-gid 0
....