---
sidebar: sidebar 
permalink: bp/saphana_aff_nfs_host_setup.html 
keywords: SUSE Linux Enterprise Server, configuration, mount points, LaMa 
summary: 本節所述的所有主機設定步驟均適用於實體伺服器上的SAP HANA環境、以及在VMware vSphere上執行的SAP HANA。 
---
= 主機設定
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./../media/


link:saphana_aff_nfs_storage_controller_setup.html["先前：儲存控制器設定。"]

本節所述的所有主機設定步驟均適用於實體伺服器上的SAP HANA環境、以及在VMware vSphere上執行的SAP HANA。



== SUSE Linux Enterprise Server的組態參數

每個SAP HANA主機上的其他核心和組態參數必須針對SAP HANA產生的工作負載進行調整。



=== SUSE Linux Enterprise Server 12和15

從SUSE Linux Enterprise Server 12 SP1開始、核心參數必須設定在/etc/syscl.d目錄的組態檔中。例如、您必須建立名稱為「91-NetApp-HANA」的組態檔。

....
net.core.rmem_max = 16777216
net.core.wmem_max = 16777216
net.ipv4.tcp_rmem = 4096 131072 16777216
net.ipv4.tcp_wmem = 4096 16384  16777216
net.core.netdev_max_backlog = 300000
net.ipv4.tcp_slow_start_after_idle=0
net.ipv4.tcp_no_metrics_save = 1
net.ipv4.tcp_moderate_rcvbuf = 1
net.ipv4.tcp_window_scaling = 1
net.ipv4.tcp_timestamps = 1
net.ipv4.tcp_sack = 1
....

NOTE: 適用於SAP OS版本的SLES隨附的Saptune可用來設定這些值。如需詳細資訊、請參閱 https://launchpad.support.sap.com/["SAP附註3024346"^] （需要SAP登入）。

如果使用NFSv3連接儲存設備、則必須在「/etc/modprobe.d/SUNrpc.conf」中設定「unrpc.tcp_ma_slot_table_entries」。如果檔案不存在、您必須先新增下列行來建立檔案：

....
options sunrpc tcp_max_slot_table_entries=128
....


== Red Hat Enterprise Linux 7.2或更新版本的組態參數

您必須針對SAP HANA產生的工作負載、在每個SAP HANA主機上調整額外的核心和組態參數。

如果使用NFSv3連接儲存設備、您必須在「/etc/modprobe.d/SUNrpc.conf」中設定參數「show rpc.tcp_ma_slot_table_entries」。如果檔案不存在、您必須先新增下列行來建立檔案：

....
options sunrpc tcp_max_slot_table_entries=128
....
從Red Hat Enterprise Linux 7.2開始、您必須在/etc/syscl.d目錄的組態檔中設定核心參數。例如、您必須建立名稱為「91-NetApp-HANA」的組態檔。

....
net.core.rmem_max = 16777216
net.core.wmem_max = 16777216
net.ipv4.tcp_rmem = 4096 131072 16777216
net.ipv4.tcp_wmem = 4096 16384  16777216
net.core.netdev_max_backlog = 300000
net.ipv4.tcp_slow_start_after_idle=0
net.ipv4.tcp_no_metrics_save = 1
net.ipv4.tcp_moderate_rcvbuf = 1
net.ipv4.tcp_window_scaling = 1
net.ipv4.tcp_timestamps = 1
net.ipv4.tcp_sack = 1
....


== 在/HANA /共享磁碟區中建立子目錄


NOTE: 以下範例顯示SID=NF2的SAP HANA資料庫。

若要建立必要的子目錄、請執行下列其中一項動作：

* 對於單一主機系統、請掛載「/HANA /共享」磁碟區、然後建立「共享」和「USR SAP」子目錄。


....
sapcc-hana-tst-06:/mnt # mount <storage-hostname>:/NF2_shared /mnt/tmp
sapcc-hana-tst-06:/mnt # cd /mnt/tmp
sapcc-hana-tst-06:/mnt/tmp # mkdir shared
sapcc-hana-tst-06:/mnt/tmp # mkdir usr-sap
sapcc-hana-tst-06:/mnt/tmp # cd ..
sapcc-hana-tst-06:/mnt # umount /mnt/tmp
....
* 對於多主機系統、請掛載「/HANA /共享」磁碟區、並為每個主機建立「共享」和「USR SAP」子目錄。
+
範例命令顯示2+1多主機HANA系統。



....
sapcc-hana-tst-06:/mnt # mount <storage-hostname>:/NF2_shared /mnt/tmp
sapcc-hana-tst-06:/mnt # cd /mnt/tmp
sapcc-hana-tst-06:/mnt/tmp # mkdir shared
sapcc-hana-tst-06:/mnt/tmp # mkdir usr-sap-host1
sapcc-hana-tst-06:/mnt/tmp # mkdir usr-sap-host2
sapcc-hana-tst-06:/mnt/tmp # mkdir usr-sap-host3
sapcc-hana-tst-06:/mnt/tmp # cd ..
sapcc-hana-tst-06:/mnt # umount /mnt/tmp
....


== 建立掛載點


NOTE: 以下範例顯示SID=NF2的SAP HANA資料庫。

若要建立所需的掛載點目錄、請執行下列其中一項動作：

* 對於單一主機系統、請建立掛載點並設定資料庫主機的權限。


....
sapcc-hana-tst-06:/ # mkdir -p /hana/data/NF2/mnt00001
sapcc-hana-tst-06:/ # mkdir -p /hana/log/NF2/mnt00001
sapcc-hana-tst-06:/ # mkdir -p /hana/shared
sapcc-hana-tst-06:/ # mkdir -p /usr/sap/NF2

sapcc-hana-tst-06:/ # chmod –R 777 /hana/log/NF2
sapcc-hana-tst-06:/ # chmod –R 777 /hana/data/NF2
sapcc-hana-tst-06:/ # chmod -R 777 /hana/shared
sapcc-hana-tst-06:/ # chmod -R 777 /usr/sap/NF2
....
* 對於多主機系統、請建立掛載點、並在所有工作者和待命主機上設定權限。下列命令範例適用於2+1多主機HANA系統。
+
** 第一工作者主機：




....
sapcc-hana-tst-06:~ # mkdir -p /hana/data/NF2/mnt00001
sapcc-hana-tst-06:~ # mkdir -p /hana/data/NF2/mnt00002
sapcc-hana-tst-06:~ # mkdir -p /hana/log/NF2/mnt00001
sapcc-hana-tst-06:~ # mkdir -p /hana/log/NF2/mnt00002
sapcc-hana-tst-06:~ # mkdir -p /hana/shared
sapcc-hana-tst-06:~ # mkdir -p /usr/sap/NF2

sapcc-hana-tst-06:~ # chmod -R 777 /hana/log/NF2
sapcc-hana-tst-06:~ # chmod -R 777 /hana/data/NF2
sapcc-hana-tst-06:~ # chmod -R 777 /hana/shared
sapcc-hana-tst-06:~ # chmod -R 777 /usr/sap/NF2
....
* 第二工作者主機：


....
sapcc-hana-tst-07:~ # mkdir -p /hana/data/NF2/mnt00001
sapcc-hana-tst-07:~ # mkdir -p /hana/data/NF2/mnt00002
sapcc-hana-tst-07:~ # mkdir -p /hana/log/NF2/mnt00001
sapcc-hana-tst-07:~ # mkdir -p /hana/log/NF2/mnt00002
sapcc-hana-tst-07:~ # mkdir -p /hana/shared
sapcc-hana-tst-07:~ # mkdir -p /usr/sap/NF2

sapcc-hana-tst-07:~ # chmod -R 777 /hana/log/NF2
sapcc-hana-tst-07:~ # chmod -R 777 /hana/data/NF2
sapcc-hana-tst-07:~ # chmod -R 777 /hana/shared
sapcc-hana-tst-07:~ # chmod -R 777 /usr/sap/NF2
....
* 待命主機：


....
sapcc-hana-tst-08:~ # mkdir -p /hana/data/NF2/mnt00001
sapcc-hana-tst-08:~ # mkdir -p /hana/data/NF2/mnt00002
sapcc-hana-tst-08:~ # mkdir -p /hana/log/NF2/mnt00001
sapcc-hana-tst-08:~ # mkdir -p /hana/log/NF2/mnt00002
sapcc-hana-tst-08:~ # mkdir -p /hana/shared
sapcc-hana-tst-08:~ # mkdir -p /usr/sap/NF2

sapcc-hana-tst-08:~ # chmod -R 777 /hana/log/NF2
sapcc-hana-tst-08:~ # chmod -R 777 /hana/data/NF2
sapcc-hana-tst-08:~ # chmod -R 777 /hana/shared
sapcc-hana-tst-08:~ # chmod -R 777 /usr/sap/NF2
....


== 掛載檔案系統

視NFS版本和ONTAP 發行版而定、必須使用不同的掛載選項。下列檔案系統必須掛載到主機：

* /hana /資料/SID/mnt0000*
* /hana / log / si/mnt0000*
* 《Hana / Shared》（《Hana /共享》）
* usr/sap/sID


下表顯示單一主機和多主機SAP HANA資料庫的不同檔案系統必須使用的NFS版本。

|===
| 檔案系統 | SAP HANA單一主機 | SAP HANA多部主機 


| /HANA /資料/SID/mnt0000* | NFSv3或NFSv4 | NFSv4. 


| /HANA /記錄/SID/mnt0000* | NFSv3或NFSv4 | NFSv4. 


| /HANA /共享 | NFSv3或NFSv4 | NFSv3或NFSv4 


| /usr/sap/sID | NFSv3或NFSv4 | NFSv3或NFSv4 
|===
下表顯示各種NFS版本和ONTAP 發行版的掛載選項。通用參數與NFS ONTAP 和SFC版本無關。


NOTE: SAP Lama需要將/usr/sap/sID目錄變成本機目錄。因此、如果您使用的是SAP Lama、請勿掛載USr/SAP/SID的NFS磁碟區。

對於NFSv3、您必須關閉NFS鎖定、以免在軟體或伺服器故障時執行NFS鎖定清除作業。

利用S多達1MB的NFS傳輸大小、可ONTAP 設定為使用此功能。具體而言、使用40GbE或更快連線至儲存系統時、您必須將傳輸大小設為1MB、才能達到預期的處理量值。

|===
| 通用參數 | NFSv3 | NFSv4. | NFS傳輸大小ONTAP 與功能 | NFS傳輸大小ONTAP 與功能8 


| rw、bg、hard、timeo=600、noatime | vers = 3、nock | vers = 4、minorversion=1、鎖定 | rsize=1048576、wsize=262144 | rsize=65536、wsize=65536 
|===

NOTE: 為提升NFSv3的讀取效能、NetApp建議您使用「nconnect = n」掛載選項、此選項適用於SUSE Linux Enterprise Server 12 SP4或更新版本、以及RedHat Enterprise Linux（RHEL）8.3或更新版本。


NOTE: 效能測試顯示、"nConnect = 8"提供良好的讀取結果。記錄寫入作業可能會因為較少的工作階段而受益、例如「nconnect = 2」。請注意、第一次從NFS伺服器掛載（IP位址）定義使用的工作階段數量。即使nconnect使用不同的值、進一步的掛載也不會變更此設定。


NOTE: NetApp支援NFSv4.1的nconnect選項、從ONTAP 功能表9.8開始。支援nconnect with NFSv4.1的第一個NFS用戶端可搭配使用SLES15SP2和RHEL 8.4。如需其他資訊、請參閱Linux廠商文件。

以下範例顯示使用NFSv3且NFS傳輸大小為1MB的單一主機SAP HANA資料庫、其SID=NF2為例。若要在系統開機期間使用「etc/stab'組態檔掛載檔案系統、請完成下列步驟：

. 將所需的檔案系統新增至「etc/stab'組態檔。
+
....
sapcc-hana-tst-06:/ # cat /etc/fstab
<storage-vif-data01>:/NF2_data_mnt00001 /hana/data/NF2/mnt00001 nfs rw,vers=3,hard,timeo=600,rsize=1048576,wsize=262144,bg,noatime,nolock 0 0
<storage-vif-log01>:/NF2_log_mnt00001 /hana/log/NF2/mnt00001 nfs rw,vers=3,hard,timeo=600,rsize=1048576,wsize=262144,bg,noatime,nolock 0 0
<storage-vif-data01>:/NF2_shared/usr-sap /usr/sap/NF2 nfs rw,vers=3,hard,timeo=600,rsize=1048576,wsize=262144,bg,noatime,nolock 0 0
<storage-vif-data01>:/NF2_shared/shared /hana/shared nfs rw,vers=3,hard,timeo=600,rsize=1048576,wsize=262144,bg,noatime,nolock 0 0
....
. 執行「mount–a」、在所有主機上掛載檔案系統。


下一個範例顯示使用NFSv4.1的多主機SAP HANA資料庫、使用SID=NF2的資料與記錄檔系統、以及使用NFSv3的「/HANA /共享」和「USP/SAP/NF2」檔案系統。NFS傳輸大小為1MB。

. 將所需的檔案系統新增至所有主機上的「etc/stb'組態檔」。
+

NOTE: 每個資料庫主機的「USP/SAP/NF2」檔案系統各不相同。以下範例顯示「/NF2_shared_usr- sap-host1」。

+
....
stlrx300s8-5:/ # cat /etc/fstab
<storage-vif-data01>:/NF2_data_mnt00001 /hana/data/NF2/mnt00001 nfs  rw,vers=4, minorversion=1,hard,timeo=600,rsize=1048576,wsize=262144,bg,noatime,lock 0 0
<storage-vif-data02>:/NF2_data_mnt00002 /hana/data/NF2/mnt00002 nfs rw,vers=4, minorversion=1,hard,timeo=600,rsize=1048576,wsize=262144,bg,noatime,lock 0 0
<storage-vif-log01>:/NF2_log_mnt00001 /hana/log/NF2/mnt00001 nfs rw,vers=4, minorversion=1,hard,timeo=600,rsize=1048576,wsize=262144,bg,noatime,lock 0 0
<storage-vif-log02>:/NF2_log_mnt00002 /hana/log/NF2/mnt00002 nfs rw,vers=4, minorversion=1,hard,timeo=600,rsize=1048576,wsize=262144,bg,noatime,lock 0 0
<storage-vif-data02>:/NF2_shared/usr-sap-host1 /usr/sap/NF2 nfs rw,vers=3,hard,timeo=600,rsize=1048576,wsize=1048576,bg,noatime,nolock 0 0
<storage-vif-data02>:/NF2_shared/shared /hana/shared nfs rw,vers=3,hard,timeo=600,rsize=1048576,wsize=1048576,bg,noatime,nolock 0 0
....
. 執行「mount–a」、在所有主機上掛載檔案系統。


link:saphana_aff_nfs_sap_hana_installation_preparations_for_nfsv4.html["接下來：NFSv4的SAP HANA安裝準備。"]
